eureka:
  instance:
    hostname: localhost

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8090

spring:
  application:
    name: recherche
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stage
    username: username
    password: password
    jpa:
      hibernate :
        ddl-auto:create
      database-platform : org.hibernate.PostgreSQLDialect
